### PR TITLE
object's first property value is undefined, it adds a comma in the be…

### PR DESCRIPTION
**Pull request by nazeemkhan77**
…gining of the json string and causes json parsing failure.

### CODE REVIEW

**Comment by jcstanaway** [comment]
We saw this when calling fastest-json-stringify with a standard Error object.  This object includes a toJSON() method, which when called, returns the following object:

image

keyList() then returns the array ['arguments', 'message', 'stack', 'type'].  The first time through the while-loop, propVal 'arguments' is undefined so it moves on to the next key.  Since this propVal is not undefined and this is not the first time through the while loop, a comma is added to the (currently empty) string causing the end result to be a malformed JSON string.  This PR is to only add the comma if the string is not currently empty.

**Comment by streamich** [comment]
Thank you! Good catch.

**Review by streamich — APPROVED** [review]

**Comment by streamich** [comment]
Should be now available as version `2.0.2`.

**Comment by nazeemkhan77** [comment]
Thank you for merging the pull request.

**Pull request merged**
